# Generated by Django 4.1 on 2022-10-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='filter_hours',
            field=models.CharField(default='[]', max_length=250),
        ),
    ]
